/**
 * Default template for codex.yaml.
 */

export function codexTemplate(): string {
  return [
    '# Codex configuration',
    '# Generated by Void',
    '',
    'model: default',
    '',
    'approval_policy: suggest',
    '',
    'providers: []',
    '',
  ].join('\n');
}
