/**
 * Default template for cowork.config.yaml.
 */

export function coworkTemplate(): string {
  return [
    '# Cowork configuration',
    '# Generated by Void',
    '',
    'version: "1.0"',
    '',
    'agents: []',
    '',
    'hooks: []',
    '',
  ].join('\n');
}
