/**
 * Default template for .cursorrules.
 */

export function cursorTemplate(): string {
  return [
    '# Cursor Rules',
    '# Generated by Void',
    '',
    '[general]',
    'Follow project conventions and coding standards.',
    '',
  ].join('\n');
}
